apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: destiny-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/ssy02060/destiny-app-config.git
    targetRevision: HEAD
    path: dev
  destionation:
    server: https://kubernetes.default.svc
    namespace: destiny
  
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    # automaticly sync
    automated:
      selfHeal: true
      prune: true
    

