apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
spec:
  selector:
    matchLabels:
      app: destiny
  replicas: 2
  template:
    metadata:
      labels:
        app: destiny
    spec:
      containers:
      - name: gateway
        image: 844148244640.dkr.ecr.ap-northeast-2.amazonaws.com/gateway:10
        ports:
        - containerPort: 80
    